name: you_chat
description: A simple chat application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  google_sign_in: ^4.5.4
  firebase_auth: ^0.18.1
  firebase_core: ^0.5.0
  provider: ^4.3.2+2
  cloud_firestore: ^0.14.0+2
  flutter_facebook_auth: "^0.2.3"
  flutter_spinkit: ^4.1.2+1
  cupertino_icons: ^1.0.0
  firebase_storage: ^4.0.1
  flutter_bloc: ^6.0.6
  redux: ^4.0.0+3
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: league-spartan
      fonts:
        - asset: assets/fonts/league-spartan.bold.ttf

  assets:
    - assets/images/